#!/bin/bash
# Rokid AoE / Claude remote launcher: token-protected relay + public WSS tunnel + QR config.
#
# Usage:
#   ./start-remote.command                         # ngrok, temp URL
#   TUNNEL_PROVIDER=cloudflare ./start-remote.command
#   NGROK_DOMAIN=your-domain.ngrok-free.app ./start-remote.command
#
# First-time ngrok setup:
#   brew install ngrok
#   ngrok config add-authtoken <your ngrok authtoken>
#
# The generated QR is secret: anyone with the URL+token can drive the relay on this Mac.
set -euo pipefail
cd "$(dirname "$0")"

PORT="${ROKID_PORT:-8788}"
PROVIDER="${TUNNEL_PROVIDER:-ngrok}"          # ngrok | cloudflare
ENV_FILE="relay/.remote.env"
GENERATED_CONFIG="config.remote.generated.json"
QR_TEXT_FILE="config.remote.qr.txt"
QR_PNG_FILE="config.remote.qr.png"
RELAY_LOG="/tmp/rokid-relay-remote.log"
TUNNEL_LOG="/tmp/rokid-${PROVIDER}.log"
DRY_RUN="${ROKID_REMOTE_DRY_RUN:-0}"
EXIT_AFTER_READY="${ROKID_REMOTE_EXIT_AFTER_READY:-0}"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "✗ Missing command: $1"
    echo "  Install it first, then rerun this script."
    exit 1
  fi
}

ensure_secret_env() {
  mkdir -p relay
  if [ ! -f "$ENV_FILE" ]; then
    local token
    token="$(openssl rand -hex 32)"
    cat > "$ENV_FILE" <<EOF
# Auto-generated by start-remote.command. Keep this file secret; it is gitignored.
ROKID_TOKEN=$token
# Optional fixed ngrok domain, e.g. your-name.ngrok-free.app. Leave empty for temporary URL.
NGROK_DOMAIN=
EOF
    chmod 600 "$ENV_FILE"
    echo "✓ Generated ${ENV_FILE} with a random ROKID_TOKEN"
  fi
  set -a; . "$ENV_FILE"; set +a
  if [ -z "${ROKID_TOKEN:-}" ]; then
    echo "✗ $ENV_FILE contains an empty ROKID_TOKEN"
    exit 1
  fi
}

cleanup_port() {
  pkill -f "ngrok http .*${PORT}" 2>/dev/null || true
  pkill -f "cloudflared tunnel --url http://localhost:${PORT}" 2>/dev/null || true
  local old_pids
  old_pids="$(lsof -tiTCP:"$PORT" -sTCP:LISTEN 2>/dev/null || true)"
  if [ -n "$old_pids" ]; then
    echo "ℹ Closing old process(es) on :$PORT: $old_pids"
    kill $old_pids 2>/dev/null || true
    sleep 1
  fi
}

start_relay() {
  : > "$RELAY_LOG"
  local claude_env=()
  if [ -n "${CLAUDE_BINARY:-}" ]; then
    claude_env+=("CLAUDE_BINARY=$CLAUDE_BINARY")
  elif command -v claude >/dev/null 2>&1; then
    claude_env+=("CLAUDE_BINARY=$(command -v claude)")
  fi

  echo "▶ Starting relay on :$PORT with token auth…"
  (
    cd relay
    env "${claude_env[@]}" ROKID_TOKEN="$ROKID_TOKEN" ROKID_PORT="$PORT" npm run dev
  ) > "$RELAY_LOG" 2>&1 &
  RELAY_PID=$!

  for _ in $(seq 1 30); do
    if ! kill -0 "$RELAY_PID" 2>/dev/null; then
      echo "✗ Relay exited early:"
      tail -100 "$RELAY_LOG" || true
      exit 1
    fi
    if lsof -nP -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; then
      echo "✓ Relay is listening on :$PORT"
      return
    fi
    sleep 1
  done
  echo "✗ Relay did not start listening on :$PORT"
  tail -100 "$RELAY_LOG" || true
  exit 1
}

start_tunnel() {
  : > "$TUNNEL_LOG"
  case "$PROVIDER" in
    ngrok)
      need_cmd ngrok
      if [ -n "${NGROK_DOMAIN:-}" ]; then
        echo "▶ Starting ngrok fixed domain: https://$NGROK_DOMAIN → localhost:$PORT"
        env -u HTTP_PROXY -u HTTPS_PROXY -u http_proxy -u https_proxy -u all_proxy \
          ngrok http "$PORT" --url="$NGROK_DOMAIN" --log=stdout > "$TUNNEL_LOG" 2>&1 &
      else
        echo "▶ Starting ngrok temporary URL → localhost:$PORT"
        env -u HTTP_PROXY -u HTTPS_PROXY -u http_proxy -u https_proxy -u all_proxy \
          ngrok http "$PORT" --log=stdout > "$TUNNEL_LOG" 2>&1 &
      fi
      TUNNEL_PID=$!
      ;;
    cloudflare|cloudflared)
      PROVIDER="cloudflare"
      need_cmd cloudflared
      echo "▶ Starting Cloudflare quick tunnel → localhost:$PORT"
      env -u HTTP_PROXY -u HTTPS_PROXY -u http_proxy -u https_proxy -u all_proxy \
        cloudflared tunnel --url "http://localhost:$PORT" > "$TUNNEL_LOG" 2>&1 &
      TUNNEL_PID=$!
      ;;
    *)
      echo "✗ Unknown TUNNEL_PROVIDER=$PROVIDER (use ngrok or cloudflare)"
      exit 1
      ;;
  esac
}

public_url_from_ngrok() {
  curl -fsS http://127.0.0.1:4040/api/tunnels 2>/dev/null \
    | node -e 'let s="";process.stdin.on("data",d=>s+=d);process.stdin.on("end",()=>{try{const j=JSON.parse(s);const u=(j.tunnels||[]).find(t=>t.proto==="https")?.public_url||""; if(u) console.log(u)}catch{}})' \
    || true
}

public_url_from_cloudflare_log() {
  grep -Eo 'https://[-a-zA-Z0-9.]+\.trycloudflare\.com' "$TUNNEL_LOG" | head -n1 || true
}

wait_public_url() {
  local public=""
  for _ in $(seq 1 45); do
    if ! kill -0 "$TUNNEL_PID" 2>/dev/null; then
      echo "✗ Tunnel exited early:"
      tail -120 "$TUNNEL_LOG" || true
      exit 1
    fi
    if [ "$PROVIDER" = "ngrok" ]; then
      public="$(public_url_from_ngrok)"
    else
      public="$(public_url_from_cloudflare_log)"
    fi
    if [ -n "$public" ]; then
      PUBLIC_URL="$public"
      return
    fi
    sleep 1
  done
  echo "✗ Tunnel did not produce a public URL. Log:"
  tail -120 "$TUNNEL_LOG" || true
  exit 1
}

write_config_and_qr() {
  WS_URL="${PUBLIC_URL/https:/wss:}"
  cat > "$GENERATED_CONFIG" <<EOF
{
  "serverUrl": "$WS_URL",
  "token": "$ROKID_TOKEN",
  "lang": "zh"
}
EOF
  chmod 600 "$GENERATED_CONFIG"
  printf 'RCLAUDE:url=%s;token=%s;lang=zh\n' "$WS_URL" "$ROKID_TOKEN" > "$QR_TEXT_FILE"
  chmod 600 "$QR_TEXT_FILE"

  rm -f "$QR_PNG_FILE"
  if command -v qrencode >/dev/null 2>&1; then
    qrencode -o "$QR_PNG_FILE" < "$QR_TEXT_FILE" || true
  elif [ -x scripts/make-qr.swift ]; then
    scripts/make-qr.swift "$QR_PNG_FILE" < "$QR_TEXT_FILE" || true
  fi
}

smoke_ws_once() {
  (cd relay && ROKID_WS_URL="$WS_URL/?token=$ROKID_TOKEN" node - <<'NODE'
const { WebSocket } = require('ws');
const url = process.env.ROKID_WS_URL;
const ws = new WebSocket(url, { headers: { 'ngrok-skip-browser-warning': 'true' } });
const timeout = setTimeout(() => { console.error('timeout'); process.exit(2); }, 12000);
ws.on('open', () => ws.send(JSON.stringify({ type: 'hello', lang: 'zh' })));
ws.on('message', (buf) => {
  const msg = JSON.parse(buf.toString());
  if (msg.type === 'sync') {
    clearTimeout(timeout);
    console.log('✓ Remote WSS hello→sync OK');
    ws.close();
    process.exit(0);
  }
});
ws.on('error', (err) => { console.error(err.message); process.exit(1); });
NODE
  )
}

smoke_ws() {
  echo "▶ Testing remote WSS handshake…"
  for attempt in $(seq 1 8); do
    if smoke_ws_once; then return; fi
    echo "  retry $attempt/8: tunnel URL exists but WSS is not ready yet"
    sleep 2
  done
  echo "✗ Remote WSS handshake failed after retries"
  tail -80 "$TUNNEL_LOG" || true
  exit 1
}

print_ready() {
  echo "────────────────────────────────────────"
  echo "  Rokid AoE Terminal · Remote Mode"
  echo "  provider: $PROVIDER"
  echo "  public WSS: $WS_URL"
  echo "  config JSON: $GENERATED_CONFIG"
  echo "  QR text: $QR_TEXT_FILE"
  [ -f "$QR_PNG_FILE" ] && echo "  QR png: $QR_PNG_FILE"
  echo "  relay log: $RELAY_LOG"
  echo "  tunnel log: $TUNNEL_LOG"
  echo "────────────────────────────────────────"
  echo "眼镜已离线时：单击打开 QR scanner → 扫描 $QR_PNG_FILE → 确认 → 自动重连。"
  echo "安全提醒：config/QR 内含 token，等同远程控制本 Mac 上的 AoE/Claude/Codex relay；不要公开。"
  echo "用完按 Ctrl+C，会关闭本次 relay/tunnel。"
}

cleanup_started() {
  kill ${TUNNEL_PID:-} ${RELAY_PID:-} 2>/dev/null || true
  local still
  still="$(lsof -tiTCP:"$PORT" -sTCP:LISTEN 2>/dev/null || true)"
  [ -n "$still" ] && kill $still 2>/dev/null || true
}

need_cmd openssl
need_cmd lsof
need_cmd node
ensure_secret_env

if [ "$DRY_RUN" = "1" ]; then
  echo "DRY_RUN_OK provider=$PROVIDER port=$PORT env=$ENV_FILE"
  exit 0
fi

cleanup_port
start_relay
start_tunnel
trap cleanup_started EXIT INT TERM
wait_public_url
write_config_and_qr
smoke_ws
print_ready
[ -f "$QR_PNG_FILE" ] && open "$QR_PNG_FILE" >/dev/null 2>&1 || true
if [ "$EXIT_AFTER_READY" = "1" ]; then
  echo "EXIT_AFTER_READY_OK"
  exit 0
fi
wait "$RELAY_PID"
