#!/bin/bash
# Rokid Claude 远程启动: 中继(带 token) + ngrok 隧道
# 用法:
#   1) 先执行一次: ngrok config add-authtoken <你的 ngrok authtoken>
#   2) 双击本文件或终端运行 ./start-remote.command
#
# 如果 relay/.remote.env 不存在，本脚本会自动生成 ROKID_TOKEN。
# 如果 NGROK_DOMAIN 为空，则使用 ngrok 临时公网域名，并自动写出 config.remote.generated.json。
set -euo pipefail
cd "$(dirname "$0")"

PORT="${ROKID_PORT:-8788}"
ENV_FILE="relay/.remote.env"
GENERATED_CONFIG="config.remote.generated.json"
QR_TEXT_FILE="config.remote.qr.txt"
NGROK_LOG="/tmp/rokid-ngrok.log"

if ! command -v ngrok >/dev/null 2>&1; then
  echo '✗ 没装 ngrok。先 brew install ngrok 并 ngrok config add-authtoken <你的authtoken>。'
  read -n 1 -s -r -p "按任意键关闭…"; exit 1
fi

mkdir -p relay
if [ ! -f "$ENV_FILE" ]; then
  TOKEN="$(openssl rand -hex 24)"
  cat > "$ENV_FILE" <<EOF
# Auto-generated by start-remote.command. Keep this file secret; it is gitignored.
ROKID_TOKEN=$TOKEN
# Optional fixed ngrok domain, e.g. your-name.ngrok-free.dev. Leave empty for temporary URL.
NGROK_DOMAIN=
EOF
  chmod 600 "$ENV_FILE"
  echo "✓ 已生成 ${ENV_FILE}（含随机 ROKID_TOKEN，已 gitignore）"
fi

set -a; . "$ENV_FILE"; set +a
if [ -z "${ROKID_TOKEN:-}" ]; then
  echo "✗ $ENV_FILE 里 ROKID_TOKEN 为空。"
  read -n 1 -s -r -p "按任意键关闭…"; exit 1
fi

CLAUDE_BIN="${CLAUDE_BINARY:-$(command -v claude || true)}"
if [ -z "$CLAUDE_BIN" ] || [ ! -x "$CLAUDE_BIN" ]; then
  echo "✗ 找不到 claude CLI。请先安装并登录 Claude Code，或设置 CLAUDE_BINARY=/path/to/claude。"
  read -n 1 -s -r -p "按任意键关闭…"; exit 1
fi

# 防止旧 ngrok/relay 占用端口或 API。只清理本项目/本端口相关进程。
pkill -f "ngrok http .*${PORT}" 2>/dev/null || true
OLD_PIDS="$(lsof -tiTCP:"$PORT" -sTCP:LISTEN 2>/dev/null || true)"
if [ -n "$OLD_PIDS" ]; then
  echo "ℹ 关闭占用 :$PORT 的旧进程: $OLD_PIDS"
  kill $OLD_PIDS 2>/dev/null || true
  sleep 1
fi

: > "$NGROK_LOG"
if [ -n "${NGROK_DOMAIN:-}" ]; then
  echo "▶ 启动 ngrok 固定域名: https://$NGROK_DOMAIN → localhost:$PORT"
  env -u HTTP_PROXY -u HTTPS_PROXY -u http_proxy -u https_proxy -u all_proxy \
    ngrok http "$PORT" --url="$NGROK_DOMAIN" --log=stdout > "$NGROK_LOG" 2>&1 &
else
  echo "▶ 启动 ngrok 临时域名 → localhost:$PORT"
  env -u HTTP_PROXY -u HTTPS_PROXY -u http_proxy -u https_proxy -u all_proxy \
    ngrok http "$PORT" --log=stdout > "$NGROK_LOG" 2>&1 &
fi
NGROK_PID=$!
trap 'kill $NGROK_PID 2>/dev/null || true' EXIT

PUBLIC_URL=""
for _ in $(seq 1 30); do
  PUBLIC_URL="$(curl -fsS http://127.0.0.1:4040/api/tunnels 2>/dev/null | jq -r '.tunnels[]? | select(.proto=="https") | .public_url' | head -n1 || true)"
  if [ -n "$PUBLIC_URL" ] && [ "$PUBLIC_URL" != "null" ]; then break; fi
  if ! kill -0 "$NGROK_PID" 2>/dev/null; then
    echo "✗ ngrok 已退出。日志如下："
    tail -80 "$NGROK_LOG" || true
    exit 1
  fi
  sleep 1
done

if [ -z "$PUBLIC_URL" ] || [ "$PUBLIC_URL" = "null" ]; then
  echo "✗ ngrok 未提供 public_url。日志如下："
  tail -80 "$NGROK_LOG" || true
  exit 1
fi

WS_URL="${PUBLIC_URL/https:/wss:}"
cat > "$GENERATED_CONFIG" <<EOF
{
  "serverUrl": "$WS_URL",
  "token": "$ROKID_TOKEN",
  "lang": "zh"
}
EOF
chmod 600 "$GENERATED_CONFIG"
printf 'RCLAUDE:url=%s;token=%s;lang=zh\n' "$WS_URL" "$ROKID_TOKEN" > "$QR_TEXT_FILE"
chmod 600 "$QR_TEXT_FILE"

if command -v qrencode >/dev/null 2>&1; then
  qrencode -o config.remote.qr.png < "$QR_TEXT_FILE" || true
elif [ -x scripts/make-qr.swift ]; then
  scripts/make-qr.swift config.remote.qr.png < "$QR_TEXT_FILE" || true
fi

echo "──────────────────────────────"
echo "  Rokid Claude · 远程启动(ngrok)"
echo "  public: $WS_URL"
echo "  config: $GENERATED_CONFIG"
echo "  QR text: $QR_TEXT_FILE"
[ -f config.remote.qr.png ] && echo "  QR png: config.remote.qr.png"
echo "──────────────────────────────"
echo "眼镜离线时单击打开 QR scanner，扫描 config QR 后会写入远程 serverUrl/token。"
echo "⚠ token 等同可远程驱动 Claude Code，请勿公开分享 config/QR。"
echo "▶ 启动中继… 看到 '鉴权: 已开启' 即就绪。用完按 Ctrl+C。"

cd relay
CLAUDE_BINARY="$CLAUDE_BIN" ROKID_TOKEN="$ROKID_TOKEN" ROKID_PORT="$PORT" npm run dev
