#!/bin/bash
# Install the reliable Rokid AoE remote stack on this Mac:
#   AoE serve (:8790) + token-protected Rokid relay (:8788) + Cloudflare named tunnel.
set -euo pipefail

ROOT="/Volumes/DATA/Development/Rokid_Claude"
HOSTNAME="${ROKID_HOSTNAME:-rokid-aoe.wickedapp.xyz}"
TUNNEL_NAME="${ROKID_TUNNEL_NAME:-rokid-aoe}"
PORT="${ROKID_PORT:-8788}"
AOE_PORT="${AOE_PORT:-8790}"
CLOUDFLARED="${CLOUDFLARED:-/opt/homebrew/bin/cloudflared}"
NODE_NPM="${NODE_NPM:-/opt/homebrew/Cellar/node/25.8.1_1/bin/npm}"
LAUNCH_DIR="$HOME/Library/LaunchAgents"
DOMAIN="gui/$(id -u)"

cd "$ROOT"
mkdir -p scripts relay logs "$LAUNCH_DIR" "$HOME/.cloudflared"

if [ ! -f relay/.remote.env ]; then
  token="$(openssl rand -hex 32)"
  cat > relay/.remote.env <<EOF
# Auto-generated by install-reliable-remote.sh. Keep secret; gitignored.
ROKID_TOKEN=$token
NGROK_DOMAIN=
EOF
  chmod 600 relay/.remote.env
fi

chmod +x scripts/aoe-serve-service.sh scripts/rokid-relay-service.sh

TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v name="$TUNNEL_NAME" '$2 == name { print $1; exit }')"
if [ -z "$TUNNEL_ID" ]; then
  cloudflared tunnel create "$TUNNEL_NAME"
  TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v name="$TUNNEL_NAME" '$2 == name { print $1; exit }')"
fi
if [ -z "$TUNNEL_ID" ]; then
  echo "Could not discover tunnel id for $TUNNEL_NAME" >&2
  exit 1
fi
cloudflared tunnel route dns --overwrite-dns "$TUNNEL_ID" "$HOSTNAME"
cat > "$HOME/.cloudflared/$TUNNEL_NAME.yml" <<EOF
tunnel: $TUNNEL_ID
credentials-file: $HOME/.cloudflared/$TUNNEL_ID.json

ingress:
  - hostname: $HOSTNAME
    service: http://localhost:$PORT
  - service: http_status:404
EOF
chmod 600 "$HOME/.cloudflared/$TUNNEL_NAME.yml"

cat > "$LAUNCH_DIR/com.rokid.aoe-serve.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.rokid.aoe-serve</string>
  <key>ProgramArguments</key><array><string>/bin/bash</string><string>$ROOT/scripts/aoe-serve-service.sh</string></array>
  <key>WorkingDirectory</key><string>$ROOT</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>/tmp/rokid-aoe-serve.log</string>
  <key>StandardErrorPath</key><string>/tmp/rokid-aoe-serve.err.log</string>
  <key>EnvironmentVariables</key><dict><key>PATH</key><string>/opt/homebrew/bin:/opt/homebrew/Cellar/node/25.8.1_1/bin:/Users/wickedapp/.brv-cli/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string></dict>
</dict></plist>
EOF

cat > "$LAUNCH_DIR/com.rokid.relay.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.rokid.relay</string>
  <key>ProgramArguments</key><array><string>/bin/bash</string><string>$ROOT/scripts/rokid-relay-service.sh</string></array>
  <key>WorkingDirectory</key><string>$ROOT</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>/tmp/rokid-relay.log</string>
  <key>StandardErrorPath</key><string>/tmp/rokid-relay.err.log</string>
  <key>EnvironmentVariables</key><dict><key>PATH</key><string>/opt/homebrew/bin:/opt/homebrew/Cellar/node/25.8.1_1/bin:/Users/wickedapp/.brv-cli/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string></dict>
</dict></plist>
EOF

cat > "$LAUNCH_DIR/com.cloudflare.rokid-aoe.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.cloudflare.rokid-aoe</string>
  <key>ProgramArguments</key><array><string>$CLOUDFLARED</string><string>--config</string><string>$HOME/.cloudflared/$TUNNEL_NAME.yml</string><string>tunnel</string><string>run</string><string>$TUNNEL_NAME</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>/tmp/cloudflared-rokid-aoe.log</string>
  <key>StandardErrorPath</key><string>/tmp/cloudflared-rokid-aoe.err.log</string>
  <key>EnvironmentVariables</key><dict><key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string></dict>
</dict></plist>
EOF
chmod 644 "$LAUNCH_DIR/com.rokid.aoe-serve.plist" "$LAUNCH_DIR/com.rokid.relay.plist" "$LAUNCH_DIR/com.cloudflare.rokid-aoe.plist"

for label in com.rokid.aoe-serve com.rokid.relay com.cloudflare.rokid-aoe; do
  launchctl bootout "$DOMAIN" "$LAUNCH_DIR/$label.plist" 2>/dev/null || true
  launchctl bootstrap "$DOMAIN" "$LAUNCH_DIR/$label.plist"
done

set -a; . relay/.remote.env; set +a
WS_URL="wss://$HOSTNAME"
cat > config.remote.generated.json <<EOF
{
  "serverUrl": "$WS_URL",
  "token": "$ROKID_TOKEN",
  "lang": "zh"
}
EOF
chmod 600 config.remote.generated.json
printf 'RCLAUDE:url=%s;token=%s;lang=zh\n' "$WS_URL" "$ROKID_TOKEN" > config.remote.qr.txt
chmod 600 config.remote.qr.txt
command -v qrencode >/dev/null 2>&1 && qrencode -o config.remote.qr.png < config.remote.qr.txt || true

echo "Installed reliable Rokid remote stack: $WS_URL"
