#!/bin/bash
set -euo pipefail
cd /Volumes/DATA/Development/Rokid_Claude
export PATH="/opt/homebrew/bin:/opt/homebrew/Cellar/node/25.8.1_1/bin:/Users/wickedapp/.brv-cli/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
ENV_FILE="relay/.remote.env"
mkdir -p relay logs
if [ ! -f "$ENV_FILE" ]; then
  token="$(/Users/wickedapp/anaconda3/bin/openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/rokid-relay-service.sh. Keep secret; gitignored.
ROKID_TOKEN=$token
NGROK_DOMAIN=
EOF
  chmod 600 "$ENV_FILE"
fi
set -a
. "$ENV_FILE"
set +a
if [ -z "${ROKID_TOKEN:-}" ]; then
  echo "ROKID_TOKEN is empty in $ENV_FILE" >&2
  exit 1
fi
cd relay
exec /opt/homebrew/Cellar/node/25.8.1_1/bin/npm run dev
